kubectl apply -f -<<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: poc-aks-secretproviderclasses-role
rules:
- apiGroups: [secrets-store.csi.x-k8s.io]
  resources: [secretproviderclasses]
  verbs: [all]

- apiGroups: [secrets-store.csi.x-k8s.io]
  resources: [secretproviderclasses/status]
  verbs: [all]

- apiGroups: [""]
  resources: [secrets]
  verbs: [all]
EOF

---
kubectl apply -f -<<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: poc-aks-secretproviderclasses-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: poc-aks-secretproviderclasses-role
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: default
EOF
