apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "poc-aks.name" . }}-sc
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode={{ .Values.storageClass.mode }}
  - file_mode={{ .Values.storageClass.mode }}
  - uid={{ .Values.storageClass.id }}
  - gid={{ .Values.storageClass.id }}
  - mfsymlinks
  - cache=strict
parameters:
  skuName: {{ .Values.storageClass.skuName }}