apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc-aks.fullname.db" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "poc-aks.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.db.port }}
  selector:
    {{- include "poc-aks.selectorLabels.db" . | nindent 4 }}
  type: {{ .Values.service.db.type }}
