apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "poc-aks.fullname.db" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "poc-aks.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "poc-aks.name" . }}-sc
  accessModes:
    - {{ .Values.storageClass.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storageClass.storage.db }}