kubectl apply -f - <<EOF
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: "poc-aks-pod-identity"                # The name of your Azure identity
spec:
  type: 0                                     # Set type: 0 for managed service identity
  resourceID: /subscriptions/b257a86c-9b05-45ac-b405-69a297df5ee2/resourcegroups/poc_aks_others_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/poc-aks-pod-identity
  clientID: "25a3d37c-0ccc-47c3-b02a-56798db37d7d" #"ea1d4737-ca6f-4342-828b-b5435a6b10d7"     # The clientId of the Azure AD identity that you created earlier
EOF

---
kubectl apply -f - <<EOF
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: poc-aks-pod-identity-binding
spec:
    azureIdentity: "poc-aks-poc-identity"       # The name of your Azure identity
    selector: poc-aks-selector
EOF

---
k delete pod nginx-secrets-store-inline --now
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-store-inline
  labels:
    aadpodidbinding: poc-aks-selector
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: poc-aks-registry-secret
EOF
k get pod -w 
k get events
