apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc-aks.fullname.db" . }}-service
  labels:
    {{- include "poc-aks.labels.db" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.db.port }}
  selector:
    app: {{ .Chart.Name }}
    tier: {{ .Values.name.db }}
  type: {{ .Values.service.db.type }}
