apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc-aks.fullname.frontend" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "poc-aks.labels.frontend" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
  selector:
    app: {{ include "poc-aks.name" . }}
    tier: {{ include "poc-aks.name.frontend" . }}
  type: {{ .Values.service.frontend.type }}
