apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc-aks.fullname.frontend" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "poc-aks.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
  selector:
    {{- include "poc-aks.selectorLabels.frontend" . | nindent 4 }}
  type: {{ .Values.service.frontend.type }}
