apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ include "poc-aks.fullname.db" . }}-deploy
  labels:
    app: poc-aks
spec:
  selector:
    matchLabels:
        app: {{ include "poc-aks.name" . }}
        tier: {{ include "poc-aks.name.db" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "poc-aks.name" . }}
        tier: {{ include "poc-aks.name.db" . }}
    spec:
      containers:
      - image: {{ .Values.image.db.repository }}:{{ .Values.image.db.tag }}
        name: {{ include "poc-aks.name.db" . }}
        args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: poc-aks-mysql-cred
              key: root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: poc-aks-mysql-cred
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: poc-aks-mysql-cred
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "poc-aks.fullname.frontend" . }}-pvc
