apiVersion: v1
kind: Service
metadata:
  name: poc-aks-frontend-service
  labels:
    app: poc-aks
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: poc-aks
    tier: frontend
  type: LoadBalancer