apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: poc-aks
spec:
  storageClassName: poc-aks-azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi