apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc-aks.fullname.db" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "poc-aks.labels.db" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.db.port }}
  selector:
    app: {{ include "poc-aks.name" . }}
    tier: {{ include "poc-aks.name.db" . }}
  type: {{ .Values.service.db.type }}
