apiVersion: apps/v1 
kind: Deployment
metadata:
  name: poc-aks-mysql
  labels:
    app: poc-aks
spec:
  selector:
    matchLabels:
      app: poc-aks
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: poc-aks
        tier: db
    spec:
      containers:
      - image: mysql:5.6
        name: poc-aks-ctr
        args:
        # - "--ignore-db-dir"
        # - "lost+found"
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: poc-aks-mysql-cred
              key: root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: poc-aks-mysql-cred
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: poc-aks-mysql-cred
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
